.github/workflows/ci-cpu.yml, ci/cmake.sh, ci/docker_env/Dockerfile, ci/run_cpp_test.sh, ci/run_python_test.sh, ci/utils.sh
- CPU CI workflow
- Build&Test in one job
=> ci add github action

src/core/impl/comp_node/cuda/comp_node.cpp
Signed-off-by: zjd1988 <942002795@qq.com>
=> assert locator.device < sd.MAX_NR_DEVICE when bool(avaiable_node) = true

.github/workflows/ci.yml, ci/run_format_check.sh
1. Add commit lint.
2. Check the python code format.
=> ci(lint): add commit lint and format check

imperative/python/megengine/tools/README.md, imperative/python/megengine/tools/benchmark_op.py, imperative/python/megengine/tools/dump_with_testcase_mge.py
=> feat(imperative): add more tools for megengine

imperative/python/megengine/functional/elemwise.py
Fix: #251
This PR add docstrings for element-wise multiplication.
=> docs(mge/functional): update functional.mul docstring

imperative/python/megengine/distributed/functional.py
将三个类似的 all_reduce 操作的说明进行了修改，参考了 PyTorch 下的 [all_reduce 文档](https://github.com/pytorch/pytorch/blob/master/torch/distributed/distributed_c10d.py#L1251)，主要修改为：
1. 增加了输入 Tensor inp 的形状必须相同的提示
2. 将 Args 中的必选项与可选项分离，按照 docstring 的格式对可选项进行了说明
3. 按照 doctest 形式增加了测试用例
翻译对比如下（以 all_reduce_max 为例）：
Summary：
Reduce tensors with max operation on each value across the specified group.
在特定的通信组间对张量上的每一位数值进行最大化的 reduce
Note:
``inp`` tensor must have identical shape in all processes across the group.
通信组内的所有进程的 `inp` 张量必须具有相同的形状。
Args:
inp (Tensor): tensor to be reduced.
`inp` (推荐传入张量): 将要被 reduce 的张量
Keyword args:
group (Group or sequence of ints): the process group to work on. Default: ``WORLD``.
通信组 (推荐传入通信组或整数序列)：需要进行 reduce 操作的通信组。 默认值为 `WORLD`
``WORLD`` group selects all processes available. …
=> docs(mge/distributed): change the allreduce related functions document

tools/evaluation_model_parallelism.py, tools/test_model_static.py
@kagome1007 @haolongzhangm please review, thanks!
=> feat(tools): add two model evaluation tools

imperative/python/megengine/functional/tensor.py
=> docs(mge/functional): update functional.ones_like docstring

imperative/python/megengine/functional/tensor.py
=> docs(mge/functional): update functional.zeros_like docstring

imperative/python/megengine/functional/elemwise.py
updata functional.clip docstring
=> docs(mge/functional): update functional.clip docstring

README.md
加文档链接。突然发现首页连个文档传送门都没有，repo 也没有 docs 目录...
=> docs(README.md): add doc web link

README_CN.md
=> docs(readme): Add key features description

imperative/python/megengine/functional/nn.py
update functional.batch_norm docstring
=> update functional.batch_norm docstring

imperative/python/megengine/functional/nn.py
fix #330 
update functional.nn.max_pool2d docstring, modified input and output description, added an example, etc.
=> docs(mge/functional): update functional.nn.max_pool2d docstring

imperative/python/megengine/functional/nn.py
fix #329 
update functional.nn.avg_pool2d docstring, modified input and output description, added an example, etc.
=> docs(mge/functional): update functional.nn.avg_pool2d docstring

imperative/python/megengine/functional/tensor.py
docs(mge/functional): update copy example
=> docs(mge/functional): update copy example

README.md
=> docs(readme): update key features description

dnn/src/common/convolution.cpp, dnn/src/fallback/convolution/algos.cpp, dnn/src/fallback/convolution/algos.h, dnn/src/fallback/convolution/col2img_helper.h, dnn/src/fallback/convolution/opr_impl.cpp, dnn/src/fallback/convolution/opr_impl.h, dnn/test/fallback/convolution.cpp
这是这个项目的代码：https://summer-ospp.ac.cn/#/org/prodetail/222940130
=> feat(dnn) add nchw44 deconv

scripts/whl/macos/macos_build_whl.sh, scripts/whl/macos/macos_whl_env_prepare.sh
开源之夏：python whl 支持 apple ARM macos
=> fix pyenv python version

README.md, README_CN.md
update python version , plz review
=> docs(readme): update python version
